# Comparison Notebook: Pyro vs. TyXe in Wireless Federated Learning

This notebook demonstrates the practical differences between using a foundational Probabilistic Programming Language (Pyro) and a high-level Bayesian Deep Learning wrapper (TyXe) when simulating a distributed framework over a wireless communication channel.

### Key Research Challenges Addressed:
1. **Direct Parameter Access:** Accessing $\mu$ and $\rho$ tensors for Federated Aggregation.
2. **Bandwidth Constraints:** Computing the Signal-to-Noise Ratio (SNR) to prune weights before transmission.
3. **Channel Disturbances:** Injecting Additive White Gaussian Noise (AWGN) directly into the transmitted parameters.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pyro
import pyro.distributions as dist
import copy

# Set random seed for reproducibility
torch.manual_seed(42)
pyro.set_rng_seed(42)

print("PyTorch Version:", torch.__version__)
print("Pyro Version:", pyro.__version__)

PyTorch Version: 2.11.0+cpu
Pyro Version: 1.9.1


## 1. The Pyro Approach: Explicit Parameter Control

In Pyro, we build custom layers where variational parameters ($\mu$ and $\rho$) are exposed explicitly as standard `nn.Parameter` objects. This allows us to intercept them mid-flight, simulate wireless channel noise, and perform parameter-wise pruning before transmitting them to the central server.

In [2]:
class PyroBayesLinear(nn.Module):
    """
    A simplified BayesByBackprop Linear Layer implemented in Pyro.
    Exposes raw variational parameters directly for FL manipulation.
    """
    def __init__(self, in_features, out_features):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        
        # Variational parameters for weights
        self.weight_mu = nn.Parameter(torch.randn(out_features, in_features) * 0.1)
        # Initialize rho to a negative value so initial sigma is small
        self.weight_rho = nn.Parameter(torch.ones(out_features, in_features) * -3.0)

    def forward(self, x):
        # Compute standard deviation using softplus transformation
        sigma = F.softplus(self.weight_rho)
        
        # Sample weights using the reparameterization trick via Pyro
        weight_dist = dist.Normal(self.weight_mu, sigma)
        sampled_weight = pyro.sample("weight", weight_dist.to_event(2))
        
        return F.linear(x, sampled_weight)

# Instantiate a mock client model
client_model_pyro = PyroBayesLinear(in_features=4, out_features=2)
print("Exposed Parameters in Pyro Layer:")
for name, param in client_model_pyro.named_parameters():
    print(f" -> {name}: shape {param.shape}")

Exposed Parameters in Pyro Layer:
 -> weight_mu: shape torch.Size([2, 4])
 -> weight_rho: shape torch.Size([2, 4])


## 2. The TyXe Dilemma: Abstracted Parameters

TyXe wraps standard PyTorch layers and hides variational parameters inside its internal execution handlers (`poutine`). While elegant for localized training, extracting specific weight distributions for wireless simulation requires navigating complex internal structures.

The cell below demonstrates conceptually how TyXe handles architecture modification, making direct tensor manipulation difficult for custom FL pipelines.

In [3]:
# Conceptual representation of TyXe's architecture abstraction
# TyXe takes a standard deterministic layer and hooks into its state externally:

deterministic_layer = nn.Linear(4, 2)
print("Standard Deterministic Parameters:")
for name, param in deterministic_layer.named_parameters():
    print(f" -> {name}: shape {param.shape}")

# TyXe wraps this architecture, redirecting weight access to a hidden guide function.
# Direct access to client parameters like weight_rho for SNR pruning is blocked 
# because the layer itself still only holds the original deterministic weight tensor shape.

Standard Deterministic Parameters:
 -> weight: shape torch.Size([2, 4])
 -> bias: shape torch.Size([2])


## 3. Simulating the Wireless FL Pipeline (Using Pyro Primitives)

Below is a complete simulation of a single communication round where a client:
1. Calculates local weight certainties via SNR: $\text{SNR}=\frac{|\mu|}{\sigma}$.
2. Compresses data by pruning low-SNR weights to respect bandwidth constraints.
3. Transmits updates over a noisy wireless channel modeled with Additive White Gaussian Noise (AWGN).
4. Aggregates updates at the central server.

In [4]:
def simulate_wireless_client_upload(layer, prune_percentile=0.5, channel_noise_std=0.01):
    """
    Simulates client-side processing and wireless channel transmission.
    """
    print("\n=== Client-Side Processing ===")
    mu = layer.weight_mu.data.clone()
    rho = layer.weight_rho.data.clone()
    sigma = F.softplus(rho)
    
    # 1. Calculate Signal-to-Noise Ratio (SNR)
    snr = torch.abs(mu) / (sigma + 1e-12)
    print("Original Mean Weights:\n", mu)
    print("Calculated Weight SNR:\n", snr)
    
    # 2. Simulate Bandwidth Constraints via SNR Pruning
    threshold = torch.quantile(snr, prune_percentile)
    prune_mask = snr < threshold
    
    # Compress by zeroing out low-confidence parameter means
    compressed_mu = mu.clone()
    compressed_mu[prune_mask] = 0.0
    print(f"\nCompressed Mean Weights (Pruned below threshold {threshold:.4f}):\n", compressed_mu)
    
    # 3. Simulate Wireless Channel Noise (AWGN)
    noise_mu = torch.randn_like(compressed_mu) * channel_noise_std
    noise_rho = torch.randn_like(rho) * channel_noise_std
    
    transmitted_mu = compressed_mu + noise_mu
    transmitted_rho = rho + noise_rho
    
    print("\n=== Transmitted over Noisy Wireless Channel ===")
    print("Received Mean Weights at Server:\n", transmitted_mu)
    
    return transmitted_mu, transmitted_rho

# Execute the simulation function
received_mu, received_rho = simulate_wireless_client_upload(
    client_model_pyro, 
    prune_percentile=0.5, 
    channel_noise_std=0.05
)


=== Client-Side Processing ===
Original Mean Weights:
 tensor([[ 0.0337,  0.0129,  0.0234,  0.0230],
        [-0.1123, -0.0186,  0.2208, -0.0638]])
Calculated Weight SNR:
 tensor([[0.6930, 0.2651, 0.4826, 0.4741],
        [2.3110, 0.3835, 4.5448, 1.3131]])

Compressed Mean Weights (Pruned below threshold 0.5878):
 tensor([[ 0.0337,  0.0000,  0.0000,  0.0000],
        [-0.1123,  0.0000,  0.2208, -0.0638]])

=== Transmitted over Noisy Wireless Channel ===
Received Mean Weights at Server:
 tensor([[ 0.0671, -0.0354, -0.0163, -0.0139],
        [-0.1334, -0.0666,  0.2026, -0.0562]])


## 4. Server-Side Federated Aggregation

Once the server collects the noisy, pruned variational parameters from the active clients, it performs a federated average across both spatial distribution parameters ($\mu$ and $\rho$) to prepare the global prior for the next communication round.

In [5]:
def server_aggregate(received_updates):
    """
    Aggregates Gaussian variational distributions from multiple clients.
    Expects a list of tuples: [(mu_1, rho_1), (mu_2, rho_2), ...]
    """
    total_clients = len(received_updates)
    
    # Initialize aggregation tensors
    avg_mu = torch.zeros_like(received_updates[0][0])
    avg_rho = torch.zeros_like(received_updates[0][1])
    
    # Sum parameters across all client streams
    for mu, rho in received_updates:
        avg_mu += mu
        avg_rho += rho
        
    # Compute average distribution configuration
    avg_mu /= total_clients
    avg_rho /= total_clients
    
    return avg_mu, avg_rho

# Mock a second client update to demonstrate aggregation
mock_client_2 = (received_mu + 0.02, received_rho - 0.1)
client_updates = [ (received_mu, received_rho), mock_client_2 ]

global_mu, global_rho = server_aggregate(client_updates)

print("=== Server Aggregated Global Distribution Parameters ===")
print("Global Mu:\n", global_mu)
print("Global Rho:\n", global_rho)

=== Server Aggregated Global Distribution Parameters ===
Global Mu:
 tensor([[ 0.0771, -0.0254, -0.0063, -0.0039],
        [-0.1234, -0.0566,  0.2126, -0.0462]])
Global Rho:
 tensor([[-3.0676, -3.0895, -3.0546, -3.0382],
        [-2.9378, -3.0209, -3.0274, -3.0179]])


## Summary Matrix for Research Direction

| Requirement | Pyro Implementation Status | TyXe Implementation Status |
| :--- | :--- | :--- |
| **Direct Tensor Access** | **Native:** Parameters are standard sub-modules accessible via `.state_dict()` or named parameters. | **Hidden:** Handled via functional abstractions making localized manual extraction difficult. |
| **Custom Loss Formatting** | **Flexible:** `Trace_ELBO` context elements can be scaled or customized step-by-step. | **Fixed:** Tied strictly to canonical optimization loops on a single node device. |
| **Channel Customization** | **High Control:** Simple to place arbitrary communication math directly between training and averaging. | **Low Control:** Designed around end-to-end local inference execution loops. |